### ISSUE TITLE
Slack Channel for app

### ISSUE THREAD

**Issue by jasper07** [sapmentors/lemonaid#1]
I find it very difficult to track conversations in SAP Jam,

Tools like Slack / HipChat etc are a better fit for software collaboration (Jam meant for content collaboration)

Can we have a Slack channel? Trello / Jira also

**Comment by jpenninkhof** [comment]
Definitely! It's actually there already: https://sapmentors.slack.com/archives/mentors_app

**Comment by gregorwolf** [comment]
You can join the SAP Mentors Slack channel at https://sapmentors-slack-invite.cfapps.eu10.hana.ondemand.com/
