### ISSUE TITLE
#Bug #Help Required - no edit button post login + not found in search 

### ISSUE THREAD

**Issue by stevelofthouse** [sapmentors/lemonaid#104]
Hi,

After chatting with Svea, it was suggested I post here for help. 

I have two issues with the mentor finder :- 

1) no edit button after login

2) cannot search for me, can only find me by scrolling down the list. 

I've tried all the usual things; different browsers, login with email, login with SAP Number, clearing caches etc,  none of which work. 

Any help would be appreciated. 

BR

Steve
(140)

**Comment by CBasis** [comment]
1. I remember that I had a similar issue in the early beginning.
The root cause was that I was maintained with a different Email in SAPMentorFinder than I was using with my S-Number    (.de vs. .com).
Therefore even after login in successfully I did not match with my own object and was therefore not able to edit myself (or even able to see the edit).

2. I tried "Steve" as well and not hit that looks like you. ;)
Sounds a bit more strange and like your master data is not in the database.   (that would explain 1. as well)

Svea, was there a verification already done that the masterdata/email is equivalent to what Steve uses for logging in?

**Comment by stevelofthouse** [comment]
Christian,

I checked my details in the SAP profile site and tried the email listed there. It logged me in just as it does with my P Number, no edit button though.

So from that I take that the details I use ( p number or email ) are correct, otherwise it wouldn’t log me in right.

BR

Steve

Stephen Lofthouse MSc BSc PGCLTHE FHEA CIPP/E

07734 553 202
stevelofthouse@outlook.com<mailto:stevelofthouse@outlook.com>

https://www.linkedin.com/in/stevelofthouse/

On 2 Mar 2018, at 15:08, Christian Braukmüller <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  I remember that I had a similar issue in the early beginning.
The root cause was that I was maintained with a different Email in SAPMentorFinder than I was using with my S-Number (.de vs. .com).
Therefore even after login in successfully I did not match with my own object and was therefore not able to edit myself (or even able to see the edit).

  2.  I tried "Steve" as well and not hit that looks like you. ;)
Sounds a bit more strange and like your master data is not in the database. (that would explain 1. as well)

Svea, was there a verification already done that the masterdata/email is equivalent to what Steve uses for logging in?

**Comment by esjewett** [comment]
I don't see Steve anywhere in the app, either in the public or non-public profiles. Does this mean that he needs to be entered? @SveaBecker?

If you are there, I think the email that the team has configured in the app needs to match the email on the user you are logging in with, so I would share that email with the mentor team and ask them to make sure you are set up using that email?

**Comment by gregorwolf** [comment]
Hi @stevelofthouse I was able to locate your profile at: https://finder.sapmentors.sap.com/#/Mentor/98cb5f35-fb7d-4c35-8daf-01a482bea4b9 . Is stevelofthouse@outlook.com the address that is used in your P-User? Regarding the issue that searching for "Stephen" as it is maintained in your profile does not return a result needs to be investigated in another issue.

**Comment by stevelofthouse** [comment]
Gregor;

The address against the P number is steve@spikynorman.co.uk<mailto:steve@spikynorman.co.uk>

BR

Steve

Stephen Lofthouse MSc BSc PGCLTHE FHEA CIPP/E

07734 553 202
stevelofthouse@outlook.com<mailto:stevelofthouse@outlook.com>

https://www.linkedin.com/in/stevelofthouse/

On 2 Mar 2018, at 21:26, Gregor Wolf <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @stevelofthouse<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstevelofthouse&data=02%7C01%7C%7C78241d7e59884f69e85408d580843b99%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636556227770311529&sdata=ZpKvTYsdKHDUoPG99V7zFJMuYFgrYPPxWk1pu6X%2F8rw%3D&reserved=0> I was able to locate your profile at: https://finder.sapmentors.sap.com/#/Mentor/98cb5f35-fb7d-4c35-8daf-01a482bea4b9<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffinder.sapmentors.sap.com%2F%23%2FMentor%2F98cb5f35-fb7d-4c35-8daf-01a482bea4b9&data=02%7C01%7C%7C78241d7e59884f69e85408d580843b99%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636556227770311529&sdata=IFm1fT9xaUyjYcZJjh6dPSYCF5qyR0DFlPr912i9VsQ%3D&reserved=0> . Is stevelofthouse@outlook.com<mailto:stevelofthouse@outlook.com> the address that is used in your P-User? Regarding the issue that searching for "Stephen" as it is maintained in your profile does not return a result needs to be investigated in another issue.

**Comment by gregorwolf** [comment]
Hi @stevelofthouse please give it a new try. I've added the E-Mail address.

**Comment by stevelofthouse** [comment]
Sorted. Thanks Gregor

Steve

Stephen Lofthouse MSc BSc PGCLTHE FHEA CIPP/E

07734 553 202
stevelofthouse@outlook.com<mailto:stevelofthouse@outlook.com>

https://www.linkedin.com/in/stevelofthouse/

On 6 Mar 2018, at 17:12, Gregor Wolf <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @stevelofthouse<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstevelofthouse&data=02%7C01%7C%7C96563ade2db44fd7236a08d583857b66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559531672479125&sdata=yp5siJLgps3XVPaG6K0AMwjYxWF00BRQEk0NFU1ImXk%3D&reserved=0> please give it a new try. I've added the E-Mail address.
