### ISSUE TITLE
Mentors profile picture

### ISSUE THREAD

**Issue by jpenninkhof** [sapmentors/lemonaid#11]
The mentors profile page should display the picture that is selected as the currently active picture on SCN.

**Comment by entmike** [comment]
@jpenninkhof - The current Gravatar approach, perhaps can we ask "Why not Gravatar?" - I think the more existing best-of-breed tooling we use (Gravatar, GoogleMaps), the easier and better and more accessible this all is?

**Comment by jpenninkhof** [comment]
I've seen that it's implemented in quite a modular fashion. If the needs arises, we can change it quite easily. But indeed, let's just stick to the Gravatars for now. Shall I close this issue, what do you think @entmike?

**Comment by jpenninkhof** [comment]
The current logic to pull mentor pictures from the web provides an almost 100% coverage. Should be good enough for the 1st milestone. Closing.
