### ISSUE TITLE
Create and remove mentors

### ISSUE THREAD

**Issue by jpenninkhof** [sapmentors/lemonaid#13]
The program team should be able to create new mentors and remove invalid entries.

**Comment by entmike** [comment]
Anything I can do to help?  I'm handy with UI5 (I think) - Wasn't sure if Slack or JAM was the place to ask to be a contributor.

**Comment by f4abap** [comment]
Also the team should be able to move mentors to alumni.

**Comment by larslanghammer** [comment]
It is now possible to create and remove mentors using the Mentor Finder UI
#60 added this functionality.

Closing this Issue for now.
