### ISSUE TITLE
Mentor detail dialog

### ISSUE THREAD

**Issue by entmike** [sapmentors/lemonaid#14]
I'm thinking a sap.m.Dialog view/fragment that upon clicking in various parts of the App, could bring up a modal dialog with:

- Mentor Name
- Mentor Type (Customer/Partner/SAP)
- Status (Active/Alum)
- Mentor Photo
- Location (if data available, I could bring in a nice Leaflet Map at bottom of dialog)
- etc

**Comment by jpenninkhof** [comment]
It starts looking good already Mike! Love what you're doing to that page :)

**Comment by entmike** [comment]
@jpenninkhof - Thanks.  I should end up getting some more free time to finish this off with all the other fields we currently have this week, last week was pretty busy for me.  Probably also I'll make a smaller version in fragment form for use in dialog popovers later.

**Comment by jpenninkhof** [comment]
I think we're looking at a detail page that's good enough for the first milestone. Let's close this and consider additional changes in new issues.
