### ISSUE TITLE
Please explain the purpose of the app in the readme.MD

### ISSUE THREAD

**Issue by steinermatt** [sapmentors/lemonaid#16]
Furthermore, please also explain how SAP Mentors can add their own data in case they want to...

**Comment by gregorwolf** [comment]
The project wiki contains also a [Requirements](https://github.com/sapmentors/lemonaid/wiki/Requirements) document. Perhaps a link to this in the readme would be enough?

**Comment by jpenninkhof** [comment]
Purpose section has been added to the readme file. Closed.
