### ISSUE TITLE
Code standards and reviews

### ISSUE THREAD

**Issue by jpenninkhof** [sapmentors/lemonaid#17]
A valid topic was raised on reviewing code that's added to the app. In some cases, code may be added that doesn't completely comply to best practices or standards. It was proposed to have an additional branche or use pull request mechanisms for code reviews.

Although this is best practice for the more 'stable' projects on Github, I have my reservations. At this moment, I think it would decrease productivity, as the number of contributions are (relatively) quite substantial.

What would you think of reversing the process. As every contribution is published on slack and also trackable in the code history, everyone is free to review the latests contributions (and I will do so myself as well), to make sure the contributions follow best practices.

What do you think, would that make sense?

**Comment by qualiture** [comment]
The "problem" with feature branches / pull requests in (forgive me for finding a better wording) loosely managed teams is they might never be validated / merged, so code never gets updated.
Maybe we should indeed aim for getting something up and running real quickly with direct commits (and have subsequent devs fix any issues / flakey coding patterns on the fly)

After we have a first version ready, we can setup proper feature branching / pull request strategy

**Comment by entmike** [comment]
This is just my perspective and I respect others' perspectives as well though...

For simple projects like this one, there's a benefit of it being a bit loose and not overly structured with too much red tape, especially during the incubation period of a project.  Everyone is kind of feeling out what their niche part to contribute is, and the coding habits of others.

I think so far everything I've seen from a coding style perspective has fallen within normal UI5 MVC patterns (using MVC, routing, mock data, formatters, etc.) So for this reason I think everybody knows what they are doing and if everyone is communicating, it is self-managing for now, especially while the clay is still soft.

**Comment by jasper07** [comment]
my two cents

start with basics, linting and testing, need a safety check to ensure that people are doing the right thing, writing clean code and adding tests for that code.

if you break the build, you fix the build! 
https://lemonaida5a504e08.hana.ondemand.com/test/integration/opaTests.qunit.html

can we get someone at SAP to donate a Shippable account so we can set up simple CI process.

SAP Internal Best Practices eg Jenkins JSUnit etc. should not be best practice for external JS development, those things are Java legacy

JSP

**Comment by qualiture** [comment]
@jasper07 I thought Jenkins is the most widely adopted "standard" for CI/CD currently, whether for JS-only or Java?

**Comment by jpenninkhof** [comment]
Actually Jenkins is already running in the background. Every commit is currently pushed to the SAP Mentors production account on http://lemonaida5a504e08.hana.ondemand.com. We could extend this job into something that does that unit tests as well I suppose?

**Comment by jasper07** [comment]
@qualiture I think Jenkins like Bamboo has only recently supported Node.js, before the official support it was quite complex to set up Node based tasks, and even today if you compare the setup for something like Travis with Jenkins it is still quite complex, given the goal of a best practice is to lead by example, maybe the example should be simple enough for others to easily follow and replicate.

**Comment by jpenninkhof** [comment]
I think we're good with the code standards etc and have found our ways. Closing this ticket.
