### ISSUE TITLE
"Mentor Since" month number / index issue

### ISSUE THREAD

**Issue by athavanraja** [sapmentors/lemonaid#27]
04-2008 is shown as March 2008
![image](https://cloud.githubusercontent.com/assets/6701793/19500481/5273ccd0-95a6-11e6-894b-83cdfb4ebf50.png)

**Comment by gregorwolf** [comment]
Seems to be the same issue as in the SITreg App: [Date selected is saved as selected date minus 1 day #2](https://github.com/sapmentors/SITregOrganizer/issues/2)

**Comment by gregorwolf** [comment]
Seems this problem can be easily fixed by adding UTC:true to the format option of the date field. See this [fix](https://github.com/sapmentors/SITregOrganizer/commit/1ac8e8ec4e14aa615599eb10d55d15a2fab9fa1d)

**Comment by larslanghammer** [comment]
Same problem as closed #21. 
Closing this Issue
