### ISSUE TITLE
Respect public flag in geocoding

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/lemonaid#29]
When #28 provides the flags for the public address information also the geocoding which influences the position of the pin on the map should respect that.

**Comment by lemaiwo** [comment]
I suppose this should only happen when the enduser is not logged in? Adding a filter to the map will not be a good solution?
,
			filters:[{
				path: 'PublicProfile',
				operator: 'EQ',
				value1: 'true'
			}]
Guess this should be changed in the java coding.

**Comment by larslanghammer** [comment]
The public geocoding now respects the privacy setting of the user.  Changes made in #63.
