### ISSUE TITLE
Mentor location not updated/geocoded.

### ISSUE THREAD

**Issue by entmike** [sapmentors/lemonaid#30]
Not sure if it's a bug or my ignorance, but here's what I noticed this morning:

After adding my address, and marking profile as public, I do not see it show up on the map.  Is the geocoding being done in batch in back end on a schedule, or should the Google Map API be doing this in real time?

**Comment by jpenninkhof** [comment]
That's correct Mike. We're still using Google's geocoding (HCP geocoding is not out of beta yet) and are quite easily hitting the geocoding api's rate limits. That's why geocoding is limited to a batch that runs only once every 24 hours.
