### ISSUE TITLE
Suggestion: Map bubbles

### ISSUE THREAD

**Issue by entmike** [sapmentors/lemonaid#31]
This may be nit-picky, but just a suggestion if it's easy:

Currently, when you click one mentor pin on the map, you get a nice bubble with a photo, etc.  However after clicking another pin, I intuitively expect the prior bubble to go away but it remains until I click the X button.  This seems counter-intuitive to how other maps handle this, and makes browsing tight clusters of Mentors more difficult.

**Comment by gregorwolf** [comment]
Issue #26 is also related to this issue.
