### ISSUE TITLE
Search in Mentor list only searches name

### ISSUE THREAD

**Issue by esjewett** [sapmentors/lemonaid#33]
Should also search number and other displayed fields, and ideally it should search by all attributes, so that I can search by instrument, for example :)

**Comment by masayuki-sekihara** [comment]
I got a request from my team members in SAP Technology RIG.  They would like to search SAP Mentors for specific experties. For exanple, HCP, Mobile, HANA, etc.

**Comment by krisho007** [comment]
Hi @all, about issue #33. We have setSizeLimit(1000) and we also expect the total list size (mentors/alumini) to be about 500. So shall we go ahead with client side filtering? that would allow us to filter/search on all the properties. I will make this change if we are fine with this suggestion.

**Comment by krisho007** [comment]
I am working on it and see that I have following properties in the 'Mentor' entity.  
1. Name 2. Number 3. Relation to SAP 4. Mentor Status. So we can filter on these properties only. It would have been great if there was a property string containing all the expertise to filter upon.
