### ISSUE TITLE
null object returned from com.sap.mentors.lemonaid.rest.User.getEmail()

### ISSUE THREAD

**Issue by grahamrobbo** [sapmentors/lemonaid#35]
While browsing through profiles I sometimes ( very randomly) get this exception.

```
"responseText": {
    "error": {
        "code": null,
        "message": {
            "lang": "en",
            "value": "while trying to invoke the method java.lang.String.toUpperCase() of a null object returned from com.sap.mentors.lemonaid.rest.User.getEmail()"
        }
    }
}
```

**Comment by esjewett** [comment]
Solution is to switch to a language without nulls. Like Javascript. ;-)

**Comment by jpenninkhof** [comment]
I've added some additional ifs around the logic where toUppercases are performed. Hope this is solved, otherwise it may need to additional debugging and case in which we'd be able to reproduce this behaviour. 

@grahamrobbo, if you see this happening again, would you mind reopening this ticket?
