### ISSUE TITLE
CSV Upload of new mentors not possible

### ISSUE THREAD

**Issue by KatarinaFischer** [sapmentors/lemonaid#42]
Hi, 
I am absolutely not able to upload this CSV to Lemonaid to create the new Mentors. 
Gregor, I thought I am doing it the same way as you showed me last week. 
But this is the error I get back 

_"Field Mismatch on row 11
Too few fields: expected 3 fields but parsed 1 "_

Also in the Testsystem https://lemonaids0001142741trial.hanatrial.ondemand.com/#/Mentors I was uploading my data, but I do not appear in the List although it says that the upload was successful!
_"Scan results
Awesome! This file is A-okay, and contains 1 records with 2 columns. There are 1 new mentors in this file, 0 mentors will be updated."_

This is quite urgent as we have to onboard the new mentors. 
Can you help me? 
Thanks, Kati

**Comment by gregorwolf** [comment]
Hi Kati,

the problem with the file you've provided me for testing is the empty line at the end. Open the file with notepad, remove the empty line and try again. I think we have to improve the error message of just ignore empty lines. What do you think @jpenninkhof ?

Best regards
Gregor

**Comment by KatarinaFischer** [comment]
If i do "UPLOAD" the CSV that looks ok I will get this message. 

_Error creating new mentor
Error occurred while creating new mentor with id 'd06072ef-05e6-3f83-4f3b-dfaafb65320e', name 'undefined': {"error":{"code":null,"message":{"lang":"en-US","value":"Unauthorized"}}}_

**Comment by gregorwolf** [comment]
When the CSV contained the column "Shirt Number" I've got this error:
{"error":{"code":null,"message":{"lang":"de-DE","value":"The request body is malformed."}}}
Without it does work.

**Comment by KatarinaFischer** [comment]
Same error even without shirt number 
Error creating new mentor
Error occurred while creating new mentor with id 'f561714b-fc2f-94a9-71ab-38f2eda1a44d', name 'undefined': {"error":{"code":null,"message":{"lang":"en-US","value":"Unauthorized"}}}

**Comment by KatarinaFischer** [comment]
When uploading the attached file, I get this error message. 
Error updating mentor
Error occurred while updating mentor with id '1a64bb3f-4321-5f15-1ce5-efcbfe2daef0', name 'undefined': {"error":{"code":null,"message":{"lang":"en-US","value":"The request body is malformed."}}}



[ChristianDrumm.txt](https://github.com/sapmentors/lemonaid/files/878306/ChristianDrumm.txt)

**Comment by larslanghammer** [comment]
I found the bug causing the issue with the shirt number. The Backend is expecting the Number to be a String, while the Frontend converts it to Integer. I will remove the conversion in the frontend and after that the csv upload with files containing a shirt number should be working again.

**Comment by gregorwolf** [comment]
OK, as some mentors do not only have a number for their shirt we have to live with that.
