### ISSUE TITLE
Integrate Twitter Wall into Lemonaid

### ISSUE THREAD

**Issue by larslanghammer** [sapmentors/lemonaid#51]
To fill the still empty Social Media Page we can integrate the the Twitter Wall pulling SAP Mentor related Tweets via an Iframe.

**Comment by gregorwolf** [comment]
I've added:

```
xmlns:html="http://www.w3.org/1999/xhtml">
	<html:iframe 
		src="https://socialmediawalls-a5a504e08.dispatcher.hana.ondemand.com/client/index.html#sap2018/collections/29659?orientation=responsive&amp;language=en&amp;period=48&amp;rall=30" 
		height="100%" width="100%"/>
```

to **SocialMedia.view.xml** but unfortunately it does not fill the full space. Perhaps @lemaiwo has an idea.

**Comment by lemaiwo** [comment]
Added 100% height to the view and made the page in the main view scrollable disabled. Should work as soon as build is complete

**Comment by gregorwolf** [comment]
Fixed, thank you @lemaiwo
