### ISSUE TITLE
Button says "Login" even after logging in

### ISSUE THREAD

**Issue by Jelena-P** [sapmentors/lemonaid#71]
Not a huge deal but IMHO the correct login status should be displayed instead of what appears to be a static Login button. I believe it's a common user expectation these days that if there is a Login/Register button then after logging in it should change and either display the current account information (like in SAP Support Launchpad) or at least it should say "Log out" or something along those lines. Screenshot is attached, it shows I can make changes (i.e. I'm already logged in) yet the button still says "Login".

![lemonaid](https://user-images.githubusercontent.com/30806731/29037487-e63ebcac-7b71-11e7-849e-ec24f60e34e9.jpg)

**Comment by gregorwolf** [comment]
Hi Jelena,
can you please provide details what OS and Browser you use?
Best regards
Gregor

**Comment by larslanghammer** [comment]
Connected to #52.
Should be fixed with #70. Please check again if it is working now.

**Comment by Jelena-P** [comment]
It was IE Windows 7. It works now. Thank you, Lars!
