### ISSUE TITLE
Search by firstname or lastname is case sensitive

### ISSUE THREAD

**Issue by murlionline** [sapmentors/lemonaid#77]
When I search for my name with lowercase "murali", it does not bring any result. When I change the search to "**M**urali", it is able to find my record.

**Comment by qmacro** [comment]
Hi Murali - this has been addressed (semi-indirectly) with the fix to https://github.com/sapmentors/lemonaid/issues/80. There are still some issues with search which I'll raise another issue for and submit a fix.

**Comment by murlionline** [comment]
Thank you
