### ISSUE TITLE
Search function does not work

### ISSUE THREAD

**Issue by GazmoGITHub** [sapmentors/lemonaid#80]
#91 Search function does not seem to work. I tried to find myself and entered first name and surname separately but could not select myself. It did not work on both scenarios where searching as an anonymous user or when logged in with my S-UserID.

**Comment by qmacro** [comment]
I've submitted a PR to address this https://github.com/sapmentors/lemonaid/pull/81

**Comment by qmacro** [comment]
PR has been merged (thanks @gregorwolf ) - search now works. 

![search](https://user-images.githubusercontent.com/73068/34143286-ea9b277e-e483-11e7-8b62-b96773081ebf.gif)
