### ISSUE TITLE
Search / filter issues

### ISSUE THREAD

**Issue by qmacro** [sapmentors/lemonaid#82]
The `$filter` value for the OData query operation on the Mentors entity set specifies a lot of properties to search across. These properties are:

- FullName
- ShirtNumber
- RelationshipToSap/Name
- MentorStatus/Name
- SapExpertise[1,2,3]/Name

Arguably only FullName and ShirtNumber are appropriate for searching; the others ought to be filterable entities with a filter mechanism that has yet to be added. 

Also, the large value for `$filter` that is created because of the multiple search properties above results in errors in the search anyway - for example, searching for 'adams' only returns DJ Adams, when in fact there are two Adams mentors (Corey Adams too). 

My suggestion is to address this by 

1. Remove inappropriate search property criteria so searching works as expected
1. Add a filter mechanism to allow filtering by RelationshipToSap, MentorStatus and SapExpertise

I'll start with point 1 today.

**Comment by gregorwolf** [comment]
I would guess that was the reason the had client side filtering as that seems to work better on this point. Would be great if we can get also 2. before change 1.

**Comment by qmacro** [comment]
Turns out that a new filter on mentor status is not needed - this is provided by the icon tab filters already (statuses: Active, Alumni, Program).
