### ISSUE TITLE
cannot add events to calendar

### ISSUE THREAD

**Issue by SveaBecker** [sapmentors/lemonaid#87]
Hi,
I think it is possible for the program team to add events to the calendar but I can't; I do not see any "NEW" button etc.
Can someone of you please check?
Thank you,
Svea
![image](https://user-images.githubusercontent.com/36245995/36105414-cde57b86-1014-11e8-8f12-cb3014645362.png)

**Comment by gregorwolf** [comment]
Hi Svea,
this event list is coming from SITreg. I think you discovered that we should enhance something here to make that clear and link i.e. to the guide on [How to create a SIT registration form with the SAP Event Registration App?](https://wiki.scn.sap.com/wiki/pages/viewpage.action?pageId=473957177).
Best regards
Gregor

**Comment by gregorwolf** [comment]
Add a description on top of the subpage that explains that this events are provided from SITreg and if you want to learn how to use SITreg to create an event check out [How to create a SIT registration form with the SAP Event Registration App?](https://wiki.scn.sap.com/wiki/pages/viewpage.action?pageId=473957177).

**Comment by SveaBecker** [comment]
Thanks, Wouter!
