### ISSUE TITLE
Attachments in mentors profile

### ISSUE THREAD

**Issue by jpenninkhof** [sapmentors/lemonaid#9]
It should be possible to add attachments to mentors profile.

**Comment by abdulbasitg** [comment]
I've started to work on this issue. I'll add UploadCollection on the UI part, but we need to add a new entity into the OData service.
@jpenninkhof I can make the changes on the Java part but don't have any experience on OData stuff on Java. Can you help me on this part ?

**Comment by jpenninkhof** [comment]
Hey @abdulbasitg. Definitely! I can try to see if I can create an attachments entity that's exposed as a media-entity. I guess that's what you need.

**Comment by jpenninkhof** [comment]
Done!
