### ISSUE TITLE
Provided info is not visible

### ISSUE THREAD

**Issue by krojzl** [sapmentors/lemonaid#90]
Not sure if it is me doing something wrong or defect in app - but I filled most of the fields but some are still not visible to public - for example following fields are filled but not visible:
- languages
- scn, twitter, slack, linkedin
- shirt type/size

**Comment by gregorwolf** [comment]
Hi @krojzl you're right. The social channels and language don't show up in the public profile. But for the T-Shirt size I think we should keep that private.

**Comment by krojzl** [comment]
I listed shirt type/size because when looking on public profile I see those field labels there but with no provided value... In case we want to keep this private - maybe the label can be hidden as well...

**Comment by lemaiwo** [comment]
shirt type/size will not be shown anymore when there is no value. If you're not logged in (so when viewing public) , the service won't return any value for these fields. Can you check if this is fine?

**Comment by krojzl** [comment]
I can confirm that shirt type and size labels are not visible anymore. I am however still unable to see social media info - is that on purpose or is that defect?

**Comment by gregorwolf** [comment]
Social Media data has to be added to the public OData Service

src/main/java/com/sap/mentors/lemonaid/odata/JPAEdmExtension.java

seems to be the right place for that.

**Comment by gregorwolf** [comment]
Thanks @lemaiwo pull request #110 fixed this issue.
