### ISSUE TITLE
Change Profile Picture in Mentor Finder

### ISSUE THREAD

**Issue by mlfarrales** [sapmentors/lemonaid#93]
@gregorwolf  how can i change my profile picture
I tried   I want to load this photo
![photo c img_4524 003](https://user-images.githubusercontent.com/19863559/36594921-0b0fe17a-1855-11e8-9593-cec52ae79538.jpg)

**Comment by gregorwolf** [comment]
Please check the FAQ at https://finder.sapmentors.sap.com/#/Help/Faq where the process how the profile pictures are determined is documented.
