### ISSUE TITLE
Drop down menue "expertise" & "topic lead"

### ISSUE THREAD

**Issue by SveaBecker** [sapmentors/lemonaid#95]
As “SAP HANA Cloud Platform” and “HANA Cloud Platform” are outdated product names they need to be replaced with the new names “SAP Cloud Platform” and topic “Cloud Platform” and probably some more...

There are quite a lot who are complaining about that... we would need someone who is familiar with all the names and just review the existing one and update them... example screenshot below:

![image](https://user-images.githubusercontent.com/36245995/36670799-aa1dd42e-1af9-11e8-8dec-6158bac2babf.png)

**Comment by steveguo1984** [comment]
Hi Seva

I can try it

Can you send me the full list?

**Comment by gregorwolf** [comment]
Hi @steveguo1984 I've already started to get this issue fixed. Please check out b3dd485 and continue the work when @SveaBecker has provided you the list.

**Comment by SveaBecker** [comment]
Hi,
Bertram Ganz from the internal Mentor team suggested to connect with the API of sap.com so that those entries will be updated automatically.... Gregor, does this make sense? I copy email from Bertram in here but it is in German, apologies, Steve. When we decide how to move forward, I can translate in English if needed:

"Aus meiner Sicht müßte der Mentor Finder das API von sap.com nutzen, um an diese Proudct oder Topic Einträge zu kommen. 
Wenn Du Dich selbst in sap.com einloggst und dann (oben rechts über das Context-Menü Deines Avatars) über „Write a Blog“ einen neuen Blog erzeugst, kannst Du ein Primary SAP Tag einfügen. Und genau diese Liste wird vom Tagging System (Semaphore Workbench) in sap.com gespeist. Diese Tags werden von einem Team upgedated (ich kenne Brian Bernard als Kontakt) und ich kann mir gut vorstellen, dass sich die SAP Mentors im Mentor finder genausen selbst taggen sollten, wie wenn sie in sap.com einen neuen Blog thematisch klassifizieren. 
  Die Integration dieser sap.com tags in den Mentor Finder könnte ich selbst nicht implementieren, dazu bin ich zu wenig Entwickler. Vielleicht hilft es aber weiter, den Kontakt zu den sap.com Kollegen herzustellen, die die Tags pflegen. Man bräuchte den Zugang zum REST-API, das auch auf sap.com genutzt wird. 
Ohne die Integration mit dem sap.com Tag-System werdet ihr entweder immer wieder den neuesten Produktnamen, Kategorien etc. hinterherhinken (das ist kaum zu schaffen) oder ihr reduziert Euch auf wenige statische Top-Level Produkt-Kategorien und haltet die Liste dann entsprechend klein."

![image](https://user-images.githubusercontent.com/36245995/36733784-f4c456d2-1bd1-11e8-8bba-8260f36cb3a6.png)

**Comment by gregorwolf** [comment]
Very good idea from Bertram. I've tried the API URL:

https://tagsuggestion.services.sap.com/api/v1/public/search

But that returns only 24 results. Calling:

https://tagsuggestion.services.sap.com/api/v1/public/search?primaryOnly=true

returns an error. And going through with different search terms i.e. starting with a:

https://tagsuggestion.services.sap.com/api/v1/public/search?searchTerm=a&&primaryOnly=true

will I think run again in the limit. So it would be great to get in touch with someone who is behind this API to get an API documentation. @SveaBecker can you please reach out to Brian? Perhaps @ok nows more.

**Comment by SveaBecker** [comment]
Additional notes from Bertram:

Hallo Svea,
mir ist noch eingefallen, dass Helmut Tammen (ich meine er ist auch SAP Mentor) einen eigenen SAP Community Tag list browser gebaut hat:
https://detammenitsapcommunitytags-p001984trial.dispatcher.hanatrial.ondemand.com/index.html?hc_reset
Diese Anwendung muss auch das REST-API von der sap.com community rufen, um an die Tags zu kommen. Da lassen sich hoffentlich Synergien nutzen. 
Herr Tammen könnte Gregor Wolf auch erklären, wie er in seiner App an die Tags und die Displaytexte rankommt. 
Grüße von Bertram

**Comment by CBasis** [comment]
Regarding the hint by Bertram about the SAP TAG BROWSER by Helmut Tammen.  
Good idea.
But not sure if Helmut is using the REST-API because in his WIKI he describes the source as an Excel-File which is then converted to an JSON to be consumed.
=>     https://github.com/htammen/de.tammenit.sap.community.tags
I'll ping him and ask.
