### ISSUE TITLE
picture does not upload

### ISSUE THREAD

**Issue by SveaBecker** [sapmentors/lemonaid#99]
profile: Agasthuri Doss: https://finder.sapmentors.sap.com/#/Mentor/bad8154f-e787-442a-982e-eb1e856e06c5
LinkedIn Profile: 
https://www.linkedin.com/in/agasthuri-61a64089/

Picture does not show up in The Mentor Finder:
![image](https://user-images.githubusercontent.com/36245995/36740290-459b7ac6-1be2-11e8-9aff-fd32cfc3cc8f.png)

**Comment by gregorwolf** [comment]
Please check the [FAQ](https://finder.sapmentors.sap.com/#/Help/Faq) entry "Where can I upload my profile image?" for a solution.
